{% set name = "fletcher" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 06b7473c655e28ab4646515e5f26436f1b388cba0da430c4d6fd7d651518c6c4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - numba
    - python
    - pandas >=0.25
    - pyarrow >=0.15

test:
  imports:
    - fletcher
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/xhochy/fletcher
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pandas ExtensionDType/Array backed by Apache Arrow
  doc_url: https://fletcher.readthedocs.io/

extra:
  recipe-maintainers:
    - xhochy
    - fjetter
