{% set name = "fletcher" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a968d174d5eb85725025777c818639ce5b02dfd724bbf9c88f1873c08b597ff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - numba >=0.49
    - pandas >=1.0
    - pyarrow >=0.17

test:
  imports:
    - fletcher
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/xhochy/fletcher
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pandas ExtensionDType/Array backed by Apache Arrow
  doc_url: https://fletcher.readthedocs.io/

extra:
  recipe-maintainers:
    - xhochy
    - fjetter
