{% set name = "fletcher" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9cc1642c62e516868e735f9259072c898fe47c154fffcb1f0d0871a38aee17cb

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools-scm
  run:
    - python
    - numba >=0.49
    - pandas >=1.0
    - pyarrow >=0.17

test:
  imports:
    - fletcher
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/xhochy/fletcher
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pandas ExtensionDType/Array backed by Apache Arrow
  doc_url: https://fletcher.readthedocs.io/

extra:
  recipe-maintainers:
    - xhochy
    - fjetter
